version: "3.9"
services:
  api:
    container_name: 'todo_app'
    build: .
    tty: true
    stdin_open: true
    depends_on:
      - "db"
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/app:delegated

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_app
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
volumes:
  db-data:
    driver: local
